"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Decaf.py']
DATA_FILES = []
OPTIONS = {
'iconfile': 
'/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns',
'plist': {'LSUIElement': True}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
